blank_issues_enabled: false
contact_links:
  - name: 📧 Gmail MCP Server Discussions
    url: https://github.com/your-username/email-mcp-server/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔧 Troubleshooting Guide
    url: https://github.com/your-username/email-mcp-server#troubleshooting
    about: Check common issues and solutions before creating an issue
  - name: 📚 Documentation
    url: https://github.com/your-username/email-mcp-server#readme
    about: Read the full documentation and usage examples
